Repository KiwiTalk/KiwiTalk, pull requests merged in 2023-10, with the labels that each got.

#1952 feat: updater
  .github/workflows/release.yml
  Cargo.lock
  backend/bin/app/Cargo.toml
  backend/bin/app/tauri.conf.json
Labels: Type: Enhancement

#1997 기기등록시 자동 로그인
  frontend/src/app/login/content/index.tsx
  frontend/src/app/login/content/login.tsx
Labels: Type: Enhancement

#1999 1분 주기로 서버에 핑 패킷 전송
  backend/bin/app/src/client/mod.rs
  backend/crates/kiwi-talk-client/src/lib.rs
  backend/crates/talk-loco-client/src/talk/session/mod.rs
Labels: Type: Enhancement

#2007 프로젝트 아키텍처 문서화
  ARCHITECTURE.md
Labels: Type: Documentation

#2010 fix(main): workaround for displaying DevTools in Linux environments
  backend/bin/app/src/main.rs
Labels: Type: Bug

#2011 feat: add chat-item UI
  frontend/src/components/chat/item/chat-image.stories.tsx
  frontend/src/components/chat/item/chat-item.stories.css.ts
  frontend/src/components/chat/item/chat-item.stories.tsx
  frontend/src/components/chat/item/icons/forum.svg
  frontend/src/components/chat/item/icons/mute.svg
  frontend/src/components/chat/item/icons/pin.svg
  frontend/src/components/chat/item/image.css.ts
  frontend/src/components/chat/item/image.tsx
  frontend/src/components/chat/item/index.css.ts
  frontend/src/components/chat/item/index.tsx
  frontend/src/components/chat/item/types.ts
  frontend/src/global.css
Labels: Type: Enhancement, Area: UI

#2013 로그인 에러 수정
  backend/crates/talk-loco-client/src/structs/user.rs
  frontend/src/app/intl/translations/ko-KR.json
  frontend/src/app/login/content/index.tsx
Labels: Type: Bug

#2027 백엔드단 친구 목록 api 및 커맨드 구현
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  backend/bin/api/Cargo.toml
  backend/bin/api/src/auth/account.rs
  backend/bin/api/src/auth/mod.rs
  backend/bin/api/src/constants.rs
  backend/bin/api/src/friend.rs
  backend/bin/api/src/lib.rs
  backend/bin/api/src/profile.rs
  backend/bin/app/Cargo.toml
  backend/bin/app/src/client/channel_list.rs
  backend/bin/app/src/client/mod.rs
  backend/bin/app/src/main.rs
  backend/bin/auth/src/lib.rs
  backend/crates/talk-api-client/examples/auth.rs
  backend/crates/talk-api-client/src/auth/mod.rs
  backend/crates/talk-api-client/src/auth/resources.rs
  backend/crates/talk-api-client/src/credential.rs
  backend/crates/talk-api-client/src/lib.rs
  backend/crates/talk-api-client/src/response.rs
  backend/crates/talk-api-internal/Cargo.toml
  backend/crates/talk-api-internal/README.md
  backend/crates/talk-api-internal/examples/auth.rs
  backend/crates/talk-api-internal/src/account.rs
  backend/crates/talk-api-internal/src/agent.rs
  backend/crates/talk-api-internal/src/auth/client.rs
  backend/crates/talk-api-internal/src/auth/mod.rs
  backend/crates/talk-api-internal/src/auth/status.rs
  backend/crates/talk-api-internal/src/auth/xvc/default.rs
  backend/crates/talk-api-internal/src/auth/xvc/mod.rs
  backend/crates/talk-api-internal/src/client.rs
  backend/crates/talk-api-internal/src/config.rs
  backend/crates/talk-api-internal/src/credential.rs
  backend/crates/talk-api-internal/src/friend.rs
  backend/crates/talk-api-internal/src/lib.rs
  backend/crates/talk-api-internal/src/profile.rs
  backend/crates/talk-loco-client/Cargo.toml
  frontend/src/app/index.tsx
  frontend/src/app/intl/translations/ko-KR.json
  frontend/src/app/login/content/device-register.tsx
  frontend/src/app/login/content/index.tsx
  frontend/src/app/login/content/passcode.tsx
  frontend/src/app/login/index.tsx
  frontend/src/app/main/index.tsx
  frontend/src/ipc/api.ts
  frontend/src/ipc/auth.ts
  frontend/src/ipc/client.ts
Labels: Type: Enhancement

#2039 사진 전송시 역직렬화 오류 수정
  backend/crates/kiwi-talk-client/src/event/channel.rs
  backend/crates/kiwi-talk-client/src/handler/mod.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
Labels: Type: Bug

#2038 로그인 프로필 및 친구 목록 구현
  frontend/src/app/components/profile/index.css.ts
  frontend/src/app/main/index.tsx
  frontend/src/app/main/menu/friend.tsx
  frontend/src/app/main/menu/friend/icons/people_alt_outline.svg
  frontend/src/app/main/menu/friend/index.css.ts
  frontend/src/app/main/menu/friend/index.tsx
  frontend/src/app/main/profile.tsx
  frontend/src/app/main/window.css.ts
  frontend/src/components/friend-item/friend-item.stories.tsx
  frontend/src/components/friend-item/index.css.ts
  frontend/src/components/friend-item/index.tsx
  frontend/src/components/side-menu/group-list/group-list.stories.tsx
  frontend/src/components/side-menu/group-list/index.tsx
  frontend/src/components/side-menu/index.css.ts
  frontend/src/components/side-menu/index.tsx
  frontend/src/ipc/api.ts
Labels: Type: Enhancement, Area: UI

#2046 프로필 이미지 열화 현상 픽스
  frontend/src/app/components/profile/index.css.ts
  frontend/src/app/components/profile/index.tsx
  frontend/src/components/friend-item/index.css.ts
  frontend/src/components/friend-item/index.tsx
Labels: Type: Bug, Area: UI

#2047 SideMenuGroupList, SideMenu 코드 정리
  frontend/src/components/side-menu/group-list/index.css.ts
  frontend/src/components/side-menu/group-list/index.tsx
  frontend/src/components/side-menu/icon-content.css.ts
  frontend/src/components/side-menu/icon-content.stories.tsx
  frontend/src/components/side-menu/icon-content.tsx
  frontend/src/components/side-menu/index.css.ts
  frontend/src/components/side-menu/index.tsx
  frontend/src/components/side-menu/item-container.css.ts
  frontend/src/components/side-menu/item-container.stories.tsx
  frontend/src/components/side-menu/item-container.tsx
Labels: Type: Maintenance

#2048 메인화면 로그아웃 기능 구현
  frontend/src/app/main/index.tsx
Labels: Type: Enhancement

#2049 InputForm css 정리
  frontend/src/components/input-form/index.css.ts
  frontend/src/components/login/screen.css.ts
  frontend/src/components/side-menu/group-list/index.css.ts
Labels: Type: Maintenance

#2051 프로필 이미지로 작은 크기 이미지 사용
  backend/bin/api/src/friend.rs
  backend/bin/api/src/profile.rs
Labels: Type: Maintenance

#2054 반환 값 없는 API 요청 실패 오류 수정
  backend/crates/talk-api-internal/src/account.rs
  backend/crates/talk-api-internal/src/auth/mod.rs
  backend/crates/talk-api-internal/src/friend.rs
  backend/crates/talk-api-internal/src/lib.rs
  backend/crates/talk-api-internal/src/profile.rs
Labels: Type: Bug

#2059 키위톡 client 모듈 개별 crate로 분리
  ARCHITECTURE.md
  Cargo.lock
  Cargo.toml
  backend/bin/app/Cargo.toml
  backend/bin/app/src/main.rs
  backend/bin/client/Cargo.toml
  backend/bin/client/src/channel_list.rs
  backend/bin/client/src/conn.rs
  backend/bin/client/src/constants.rs
  backend/bin/client/src/event.rs
  backend/bin/client/src/handler.rs
  backend/bin/client/src/lib.rs
  backend/bin/system/src/lib.rs
  backend/crates/headless-talk/Cargo.toml
  backend/crates/headless-talk/README.md
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/channel/normal/user.rs
  backend/crates/headless-talk/src/channel/open.rs
  backend/crates/headless-talk/src/channel/updater.rs
  backend/crates/headless-talk/src/channel/user.rs
  backend/crates/headless-talk/src/chat/builder.rs
  backend/crates/headless-talk/src/chat/mod.rs
  backend/crates/headless-talk/src/config.rs
  backend/crates/headless-talk/src/database/channel/mod.rs
  backend/crates/headless-talk/src/database/channel/normal/mod.rs
  backend/crates/headless-talk/src/database/channel/normal/user.rs
  backend/crates/headless-talk/src/database/channel/open/mod.rs
  backend/crates/headless-talk/src/database/channel/open/model.rs
  backend/crates/headless-talk/src/database/channel/user.rs
  backend/crates/headless-talk/src/database/chat.rs
  backend/crates/headless-talk/src/database/migrations/v0.1.0.sql
  backend/crates/headless-talk/src/database/mod.rs
  backend/crates/headless-talk/src/database/pool.rs
  backend/crates/headless-talk/src/error.rs
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/event/mod.rs
  backend/crates/headless-talk/src/handler/error.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/talk-loco-client/README.md
Labels: Type: Maintenance

#2060 tauri-plugin-log 사용
  Cargo.lock
  backend/bin/app/Cargo.toml
  backend/bin/app/src/main.rs
  frontend/src/index.tsx
  package.json
  pnpm-lock.yaml
Labels: Type: Enhancement

#2058 채팅방 리스트 일부 구현
  frontend/src/app/main/menu/chat.tsx
Labels: Type: Enhancement

#2071 채팅방을 구현하는데 필요한 컴포넌트 추가
  frontend/kiwitalk.d.ts
  frontend/src/assets/icons/search.svg
  frontend/src/assets/icons/user.svg
  frontend/src/features/theme/classes.css.ts
  frontend/src/pages/main/_components/profile/index.ts
  frontend/src/pages/main/_components/profile/profile.css.ts
  frontend/src/pages/main/_components/profile/profile.stories.css.ts
  frontend/src/pages/main/_components/profile/profile.stories.tsx
  frontend/src/pages/main/_components/profile/profile.tsx
  frontend/src/pages/main/_components/sidebar/sidebar.css.ts
  frontend/src/pages/main/channel/_assets/icons/add-chat.svg
  frontend/src/pages/main/channel/_components/channel-item/channel-item.css.ts
  frontend/src/pages/main/channel/_components/channel-item/channel-item.stories.css.ts
  frontend/src/pages/main/channel/_components/channel-item/channel-item.stories.tsx
  frontend/src/pages/main/channel/_components/channel-item/channel-item.tsx
  frontend/src/pages/main/channel/_components/channel-item/index.ts
  frontend/src/pages/main/channel/_components/channel-list/channel-list.css.ts
  frontend/src/pages/main/channel/_components/channel-list/channel-list.stories.css.ts
  frontend/src/pages/main/channel/_components/channel-list/channel-list.stories.tsx
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
  frontend/src/pages/main/channel/_types/channel-list-item.ts
  frontend/src/pages/main/channel/_types/index.ts
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: Area: UI

#2083 v2 디자인 적용
  Cargo.lock
  backend/bin/app/Cargo.toml
  backend/bin/app/src/main.rs
  frontend/src/features/config/config-context.ts
  frontend/src/features/config/config-provider.tsx
  frontend/src/features/config/index.ts
  frontend/src/features/style-reset/style-reset.css.ts
  frontend/src/features/theme/vars.css.ts
  frontend/src/global.css
  frontend/src/index.tsx
  frontend/src/pages/_components/window-controls/window-controls.css.ts
  frontend/src/pages/_components/window-controls/window-controls.tsx
  frontend/src/pages/index.ts
  frontend/src/pages/layout.css.ts
  frontend/src/pages/layout.tsx
  frontend/src/pages/login/index.ts
  frontend/src/pages/login/page.tsx
  frontend/src/pages/main/_components/sidebar/sidebar.tsx
  frontend/src/pages/main/_utils/index.ts
  frontend/src/pages/main/_utils/useReady.tsx
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
  frontend/src/pages/main/channel/_types/channel-list-item.ts
  frontend/src/pages/main/channel/chat/index.ts
  frontend/src/pages/main/channel/chat/page.css.ts
  frontend/src/pages/main/channel/chat/page.tsx
  frontend/src/pages/main/channel/index.ts
  frontend/src/pages/main/channel/page.css.ts
  frontend/src/pages/main/channel/page.tsx
  frontend/src/pages/main/index.ts
  frontend/src/pages/main/page.css.ts
  frontend/src/pages/main/page.tsx
  frontend/src/pages/page.tsx
  package.json
  pnpm-lock.yaml
Labels: Area: UI, hacktoberfest-accepted

#2085 Common UI 작성
  Cargo.lock
  backend/bin/app/Cargo.toml
  backend/bin/app/src/main.rs
  backend/bin/app/tauri.conf.json
  frontend/src/features/style-reset/index.ts
  frontend/src/features/style-reset/mac.css.ts
  frontend/src/features/style-reset/mac.ts
  frontend/src/features/theme/vars.css.ts
  frontend/src/index.tsx
  frontend/src/pages/main/page.tsx
  frontend/src/ui-common/button/button.css.ts
  frontend/src/ui-common/button/button.stories.css.ts
  frontend/src/ui-common/button/button.stories.tsx
  frontend/src/ui-common/button/button.tsx
  frontend/src/ui-common/button/index.ts
  frontend/src/ui-common/input/index.ts
  frontend/src/ui-common/input/input.css.ts
  frontend/src/ui-common/input/input.stories.css.ts
  frontend/src/ui-common/input/input.stories.tsx
  frontend/src/ui-common/input/input.tsx
Labels: Area: UI, hacktoberfest-accepted

#2092 Theme 고도화
  frontend/src/features/theme/classes.css.ts
  frontend/src/features/theme/transition.css.ts
  frontend/src/features/theme/typography.css.ts
  frontend/src/features/theme/vars.css.ts
  frontend/src/pages/_components/window-controls/window-controls.css.ts
  frontend/src/pages/_components/window-controls/window-controls.tsx
  frontend/src/pages/layout.css.ts
  frontend/src/pages/login/_components/kiwi-background/kiwi-background.css.ts
  frontend/src/pages/login/_components/login-stepper/login-stepper.css.ts
  frontend/src/pages/login/_components/login-stepper/login-stepper.stories.css.ts
  frontend/src/pages/login/device-register/_components/passcode/passcode.css.ts
  frontend/src/pages/login/device-register/_components/passcode/passcode.stories.css.ts
  frontend/src/pages/login/end/page.css.ts
  frontend/src/pages/login/list/_components/card/login-card.css.ts
  frontend/src/pages/login/list/page.css.ts
  frontend/src/pages/login/page.css.ts
  frontend/src/pages/main/_components/profile/profile.css.ts
  frontend/src/pages/main/_components/sidebar/sidebar.css.ts
  frontend/src/pages/main/channel/chat/page.css.ts
  frontend/src/ui-common/button/button.css.ts
  frontend/src/ui-common/input/input.css.ts
Labels: Area: UI

#2093 ScrollArea 구현
  frontend/src/pages/main/channel/_components/channel-list/channel-list.stories.css.ts
  frontend/src/pages/main/channel/_components/channel-list/channel-list.stories.tsx
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
  frontend/src/ui-common/scroll-area/index.ts
  frontend/src/ui-common/scroll-area/scroll-area.css.ts
  frontend/src/ui-common/scroll-area/scroll-area.stories.css.ts
  frontend/src/ui-common/scroll-area/scroll-area.stories.tsx
  frontend/src/ui-common/scroll-area/scroll-area.tsx
  frontend/src/ui-common/scroll-area/scroll-thumb.css.ts
  frontend/src/ui-common/scroll-area/scroll-thumb.tsx
  frontend/src/ui-common/scroll-area/utils.ts
Labels: Area: UI, hacktoberfest-accepted

#2095 친구 페이지
  frontend/src/api/_types/chat.ts
  frontend/src/api/api.ts
  frontend/src/assets/translations/ko-KR.json
  frontend/src/features/style-reset/style-reset.css.ts
  frontend/src/pages/main/_components/profile/profile.css.ts
  frontend/src/pages/main/_components/profile/profile.tsx
  frontend/src/pages/main/channel/page.tsx
  frontend/src/pages/main/friend/_assets/icons/add-user.svg
  frontend/src/pages/main/friend/_components/friend-item/friend-item.css.ts
  frontend/src/pages/main/friend/_components/friend-item/friend-item.stories.css.ts
  frontend/src/pages/main/friend/_components/friend-item/friend-item.stories.tsx
  frontend/src/pages/main/friend/_components/friend-item/friend-item.tsx
  frontend/src/pages/main/friend/_components/friend-item/index.ts
  frontend/src/pages/main/friend/_components/friend-list/friend-list.css.ts
  frontend/src/pages/main/friend/_components/friend-list/friend-list.stories.css.ts
  frontend/src/pages/main/friend/_components/friend-list/friend-list.stories.tsx
  frontend/src/pages/main/friend/_components/friend-list/friend-list.tsx
  frontend/src/pages/main/friend/_components/friend-list/index.ts
  frontend/src/pages/main/friend/index.ts
  frontend/src/pages/main/friend/page.css.ts
  frontend/src/pages/main/friend/page.tsx
  frontend/src/pages/page.tsx
  frontend/src/ui-common/scroll-area/scroll-area.css.ts
  frontend/src/ui-common/scroll-area/scroll-area.tsx
Labels: Area: UI, hacktoberfest-accepted

#2103 친구 목록 레이아웃 깨지는 현상 수정
  frontend/src/pages/main/page.css.ts
Labels: Type: Bug

#2105 채팅방 ipc 구현
  Cargo.lock
  backend/bin/client/Cargo.toml
  backend/bin/client/src/channel.rs
  backend/bin/client/src/lib.rs
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/channel/open.rs
  backend/crates/headless-talk/src/conn.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/headless-talk/src/updater/mod.rs
  backend/crates/talk-loco-client/src/talk/session/channel/chat_on.rs
  backend/crates/talk-loco-client/src/talk/session/channel/mod.rs
  backend/crates/talk-loco-client/src/talk/session/channel/normal/mod.rs
  backend/crates/talk-loco-client/src/talk/session/channel/open/mod.rs
  backend/crates/talk-loco-client/src/talk/session/mod.rs
  frontend/src/api/client/channel.ts
  frontend/src/api/client/client.ts
  frontend/src/api/client/index.ts
  frontend/src/api/index.ts
  frontend/src/pages/main/_components/sidebar/sidebar.tsx
  frontend/src/pages/main/_utils/useReady.tsx
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
  frontend/src/pages/main/page.tsx
Labels: Type: Enhancement

#2107 채팅방 나가기 및 삭제된 채팅방 정리 기능 추가
  backend/bin/client/src/constants.rs
  backend/bin/client/src/lib.rs
  backend/crates/headless-talk/Cargo.toml
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/database/model/channel/mod.rs
  backend/crates/headless-talk/src/database/model/user/mod.rs
  backend/crates/headless-talk/src/database/model/user/normal.rs
  backend/crates/headless-talk/src/init/config.rs
  backend/crates/headless-talk/src/init/mod.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/headless-talk/src/updater/channel/mod.rs
  backend/crates/headless-talk/src/updater/channel/normal.rs
  backend/crates/headless-talk/src/updater/list.rs
  backend/crates/headless-talk/src/updater/mod.rs
Labels: Type: Bug, Type: Enhancement

#2112 Fix korean typo and add english support
  frontend/src/assets/translations/en-US.json
  frontend/src/assets/translations/ko-KR.json
Labels: Type: Documentation

#2113 유저 watermark가 초기화 되는 문제 수정
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/database/model/user/mod.rs
  backend/crates/headless-talk/src/database/model/user/normal.rs
Labels: Type: Bug

#2115 Actually show errror message.
  ARCHITECTURE.md
  frontend/src/pages/login/login/page.tsx
Labels: Type: Bug, Type: Documentation

#2117 TalkNormalChannel::users 메서드 제거
  backend/bin/client/src/channel.rs
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/talk-loco-client/src/talk/session/channel/chat_on.rs
Labels: Type: Maintenance

#2119 CHATONROOM 패킷 타입 수정
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/updater/channel/mod.rs
  backend/crates/headless-talk/src/updater/channel/normal.rs
  backend/crates/headless-talk/src/updater/list.rs
  backend/crates/talk-loco-client/src/talk/session/channel/chat_on.rs
Labels: Type: Maintenance

#2118 fix(main): disable `transparent` effect on Linux
  backend/bin/app/src/main.rs
Labels: Type: Enhancement

#2121 traymenu: Add explicit Focus Window entry.
  backend/bin/app/src/main.rs
Labels: Type: Bug

#2124 읽음수가 유저 정보를 가져온 후에 업데이트 되던것 수정
  backend/crates/headless-talk/src/lib.rs
Labels: Type: Bug

#2125 viewModel 리팩토링
  frontend/src/pages/_components/window-controls/window-controls.stories.tsx
  frontend/src/pages/_components/window-controls/window-controls.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/main/_components/sidebar/sidebar.stories.tsx
  frontend/src/pages/main/_components/sidebar/sidebar.tsx
  frontend/src/pages/main/_hooks/index.ts
  frontend/src/pages/main/_hooks/useReady.tsx
  frontend/src/pages/main/_hooks/useSidebar.ts
  frontend/src/pages/main/channel/_components/channel-list/channel-list.stories.tsx
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
  frontend/src/pages/main/channel/_hooks/index.ts
  frontend/src/pages/main/channel/_hooks/useChannelList.ts
  frontend/src/pages/main/channel/page.tsx
  frontend/src/pages/main/friend/_components/friend-list/friend-list.stories.tsx
  frontend/src/pages/main/friend/_components/friend-list/friend-list.tsx
  frontend/src/pages/main/friend/_hooks/index.ts
  frontend/src/pages/main/friend/_hooks/useFriendList.ts
  frontend/src/pages/main/friend/page.tsx
  frontend/src/pages/main/page.tsx
Labels: Type: Enhancement

#2127 fix(frontend): `VirtualList` 스크롤 싱크 문제 해결
  frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
  frontend/src/pages/main/channel/chat/page.tsx
  frontend/src/ui-common/virtual-list/virtual-list.stories.tsx
  frontend/src/ui-common/virtual-list/virtual-list.tsx
Labels: Type: Bug, Area: UI
