Repository KiwiTalk/KiwiTalk, pull requests merged in 2023-11, with the labels that each got.

#2133 채팅 이벤트 동기화
  backend/crates/headless-talk/src/database/model/channel/meta.rs
  backend/crates/headless-talk/src/database/model/chat.rs
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/event/mod.rs
  backend/crates/headless-talk/src/handler/error.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/headless-talk/src/init/mod.rs
  backend/crates/headless-talk/src/updater/channel/mod.rs
  backend/crates/talk-loco-client/src/talk/channel.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
Labels: Type: Enhancement

#2136 spawn_transaction 추가
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/database/mod.rs
  backend/crates/headless-talk/src/database/model/channel/meta.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/headless-talk/src/updater/list.rs
Labels: Type: Maintenance

#2137 나간 채팅방 삭제
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
  backend/crates/talk-loco-client/src/talk/stream/mod.rs
Labels: Type: Enhancement

#2140 단일 인스턴스만 실행 허용
  Cargo.lock
  backend/bin/app/Cargo.toml
  backend/bin/app/src/main.rs
Labels: Type: Enhancement

#2132 `ChatType`별 메시지
  frontend/src/assets/translations/ko-KR.json
  frontend/src/pages/main/channel/chat/_assets/icons/chart.svg
  frontend/src/pages/main/channel/chat/_assets/icons/file.svg
  frontend/src/pages/main/channel/chat/_assets/icons/music.svg
  frontend/src/pages/main/channel/chat/_assets/icons/photo.svg
  frontend/src/pages/main/channel/chat/_assets/icons/pie_chart.svg
  frontend/src/pages/main/channel/chat/_assets/icons/text.svg
  frontend/src/pages/main/channel/chat/_components/message-group/index.ts
  frontend/src/pages/main/channel/chat/_components/message-group/message-group.css.ts
  frontend/src/pages/main/channel/chat/_components/message-group/message-group.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message-group/message-group.tsx
  frontend/src/pages/main/channel/chat/_components/message-list/message-list.stories.css.ts
  frontend/src/pages/main/channel/chat/_components/message-list/message-list.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message-list/message-list.tsx
  frontend/src/pages/main/channel/chat/_components/message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/message.stories.css.ts
  frontend/src/pages/main/channel/chat/_components/message/message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/attachment-message/attachment-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/attachment-message/attachment-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/attachment-message/attachment-message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/attachment-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/image-message/image-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/image-message/image-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/image-message/image-message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/image-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/reply-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/reply-message/reply-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/reply-message/reply-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/reply-message/reply-message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/text-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/text-message/text-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/text-message/text-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/text-message/text-message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/unknown-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/unknown-message/unknown-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/unknown-message/unknown-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/unknown-message/unknown-message.tsx
  frontend/src/pages/main/channel/chat/_hooks/useChatFactory.ts
  frontend/src/pages/main/channel/chat/_hooks/useMessageList.ts
  frontend/src/pages/main/channel/chat/_utils/chat-factory.tsx
  frontend/src/pages/main/channel/chat/_utils/mock-channel.ts
  frontend/src/pages/main/channel/chat/page.tsx
  frontend/src/ui-common/button/button.tsx
  package.json
  pnpm-lock.yaml
Labels: Type: Enhancement, Area: UI

#2151 이모티콘 지원
  backend/bin/app/tauri.conf.json
  frontend/src/pages/main/channel/chat/_components/message-group/message-group.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/emoticon-message/emoticon-message.css.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/emoticon-message/emoticon-message.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/emoticon-message/emoticon-message.tsx
  frontend/src/pages/main/channel/chat/_components/message/typed/emoticon-message/index.ts
  frontend/src/pages/main/channel/chat/_components/message/typed/index.ts
  frontend/src/pages/main/channel/chat/_utils/chat-factory.tsx
Labels: Type: Enhancement, Area: UI

#2155 채널 목록을 마지막 채팅 시간 기준으로 내림차순 정렬
  frontend/src/pages/main/channel/_components/channel-list/channel-list.tsx
Labels: Type: Enhancement, Area: UI

#2139 ipc 리펙터링 및 실시간 채팅방 정보 업데이트
  Cargo.lock
  backend/bin/app/src/main.rs
  backend/bin/client/Cargo.toml
  backend/bin/client/src/channel.rs
  backend/bin/client/src/channel/mod.rs
  backend/bin/client/src/channel/normal.rs
  backend/bin/client/src/channel_list.rs
  backend/bin/client/src/event.rs
  backend/bin/client/src/handler.rs
  backend/bin/client/src/lib.rs
  backend/bin/resource/Cargo.toml
  backend/bin/resource/src/lib.rs
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/channel/open.rs
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/event/mod.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/headless-talk/src/init/mod.rs
  backend/crates/headless-talk/src/lib.rs
  backend/crates/headless-talk/src/task.rs
  backend/crates/talk-loco-client/src/talk/openlink/mod.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
  frontend/src/api/_types/client.ts
  frontend/src/api/client/channel.ts
  frontend/src/api/client/client.ts
  frontend/src/pages/main/_hooks/index.ts
  frontend/src/pages/main/_hooks/useChannelEvent.ts
  frontend/src/pages/main/_hooks/useEvent.ts
  frontend/src/pages/main/_hooks/useReady.tsx
  frontend/src/pages/main/channel/_hooks/useChannelList.ts
  frontend/src/pages/main/channel/chat/_components/message-group/message-group.stories.tsx
  frontend/src/pages/main/channel/chat/_components/message-list/message-list.stories.tsx
  frontend/src/pages/main/channel/chat/_hooks/useChannel.ts
  frontend/src/pages/main/channel/chat/_hooks/useMessageList.ts
  frontend/src/pages/main/channel/chat/_utils/chat-factory.tsx
  frontend/src/pages/main/channel/chat/_utils/mock-channel.ts
  frontend/src/pages/main/channel/chat/page.tsx
  frontend/src/pages/main/page.tsx
Labels: Type: Enhancement, Type: Maintenance

#2161 UI 실시간 업데이트
  frontend/src/api/_types/chat.ts
  frontend/src/pages/main/_hooks/useReady.tsx
  frontend/src/pages/main/_utils/index.ts
  frontend/src/pages/main/_utils/self-event.ts
  frontend/src/pages/main/channel/_hooks/useChannelList.ts
  frontend/src/pages/main/channel/chat/_hooks/index.ts
  frontend/src/pages/main/channel/chat/_hooks/useChannelMembers.ts
  frontend/src/pages/main/channel/chat/page.tsx
Labels: Type: Enhancement, Area: UI

#2168 저장되는 미리보기 유저 수 조정
  Cargo.lock
  backend/bin/client/Cargo.toml
  backend/bin/client/src/channel_list.rs
  backend/crates/headless-talk/Cargo.toml
  backend/crates/headless-talk/src/channel/mod.rs
  backend/crates/headless-talk/src/updater/list.rs
Labels: Type: Maintenance

#2169 채팅방 meta 정보 전달
  backend/bin/client/src/channel/normal.rs
  backend/crates/headless-talk/src/channel/normal/mod.rs
  backend/crates/headless-talk/src/channel/open.rs
  backend/crates/headless-talk/src/database/model/channel/meta.rs
  frontend/src/api/client/channel.ts
Labels: Type: Enhancement

#2170 일반 채팅방, 나와의 채팅방 생성 구현
  backend/bin/client/src/handler.rs
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/talk-loco-client/src/client/media/io.rs
  backend/crates/talk-loco-client/src/talk/session/channel/info.rs
  backend/crates/talk-loco-client/src/talk/session/create.rs
  backend/crates/talk-loco-client/src/talk/session/mod.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
  backend/crates/talk-loco-client/src/talk/stream/mod.rs
Labels: Type: Enhancement

#2171 채팅방 유저 참가, 나가기 동기화
  backend/bin/client/src/handler.rs
  backend/crates/headless-talk/src/event/channel.rs
  backend/crates/headless-talk/src/handler/mod.rs
  backend/crates/talk-loco-client/src/client/media/io.rs
  backend/crates/talk-loco-client/src/talk/session/channel/info.rs
  backend/crates/talk-loco-client/src/talk/stream/command.rs
  backend/crates/talk-loco-client/src/talk/stream/mod.rs
Labels: Type: Enhancement

#2185 Translations
  .github/workflows/prettier.yml
  .gitignore
  .prettierrc
  frontend/src/assets/translations/en-US.json
  frontend/src/assets/translations/ko-KR.json
  package.json
  pnpm-lock.yaml
Labels: Type: Enhancement, Area: UI
